	de10lite_sopc u0 (
		.avl_dmem_waitrequest   (<connected-to-avl_dmem_waitrequest>),   //        avl_dmem.waitrequest
		.avl_dmem_readdata      (<connected-to-avl_dmem_readdata>),      //                .readdata
		.avl_dmem_readdatavalid (<connected-to-avl_dmem_readdatavalid>), //                .readdatavalid
		.avl_dmem_response      (<connected-to-avl_dmem_response>),      //                .response
		.avl_dmem_burstcount    (<connected-to-avl_dmem_burstcount>),    //                .burstcount
		.avl_dmem_writedata     (<connected-to-avl_dmem_writedata>),     //                .writedata
		.avl_dmem_address       (<connected-to-avl_dmem_address>),       //                .address
		.avl_dmem_write         (<connected-to-avl_dmem_write>),         //                .write
		.avl_dmem_read          (<connected-to-avl_dmem_read>),          //                .read
		.avl_dmem_byteenable    (<connected-to-avl_dmem_byteenable>),    //                .byteenable
		.avl_dmem_debugaccess   (<connected-to-avl_dmem_debugaccess>),   //                .debugaccess
		.avl_imem_waitrequest   (<connected-to-avl_imem_waitrequest>),   //        avl_imem.waitrequest
		.avl_imem_readdata      (<connected-to-avl_imem_readdata>),      //                .readdata
		.avl_imem_readdatavalid (<connected-to-avl_imem_readdatavalid>), //                .readdatavalid
		.avl_imem_response      (<connected-to-avl_imem_response>),      //                .response
		.avl_imem_burstcount    (<connected-to-avl_imem_burstcount>),    //                .burstcount
		.avl_imem_writedata     (<connected-to-avl_imem_writedata>),     //                .writedata
		.avl_imem_address       (<connected-to-avl_imem_address>),       //                .address
		.avl_imem_write         (<connected-to-avl_imem_write>),         //                .write
		.avl_imem_read          (<connected-to-avl_imem_read>),          //                .read
		.avl_imem_byteenable    (<connected-to-avl_imem_byteenable>),    //                .byteenable
		.avl_imem_debugaccess   (<connected-to-avl_imem_debugaccess>),   //                .debugaccess
		.bld_id_export          (<connected-to-bld_id_export>),          //          bld_id.export
		.core_clk_freq_export   (<connected-to-core_clk_freq_export>),   //   core_clk_freq.export
		.cpu_clk_out_clk        (<connected-to-cpu_clk_out_clk>),        //     cpu_clk_out.clk
		.cpu_rst_out_reset_n    (<connected-to-cpu_rst_out_reset_n>),    //     cpu_rst_out.reset_n
		.osc_50_clk             (<connected-to-osc_50_clk>),             //          osc_50.clk
		.pio_led_export         (<connected-to-pio_led_export>),         //         pio_led.export
		.pio_sw_export          (<connected-to-pio_sw_export>),          //          pio_sw.export
		.pll_reset              (<connected-to-pll_reset>),              //             pll.reset
		.pwrup_rst_n_out_export (<connected-to-pwrup_rst_n_out_export>), // pwrup_rst_n_out.export
		.sdram_addr             (<connected-to-sdram_addr>),             //           sdram.addr
		.sdram_ba               (<connected-to-sdram_ba>),               //                .ba
		.sdram_cas_n            (<connected-to-sdram_cas_n>),            //                .cas_n
		.sdram_cke              (<connected-to-sdram_cke>),              //                .cke
		.sdram_cs_n             (<connected-to-sdram_cs_n>),             //                .cs_n
		.sdram_dq               (<connected-to-sdram_dq>),               //                .dq
		.sdram_dqm              (<connected-to-sdram_dqm>),              //                .dqm
		.sdram_ras_n            (<connected-to-sdram_ras_n>),            //                .ras_n
		.sdram_we_n             (<connected-to-sdram_we_n>),             //                .we_n
		.sdram_clk_out_clk      (<connected-to-sdram_clk_out_clk>),      //   sdram_clk_out.clk
		.soc_reset_n            (<connected-to-soc_reset_n>),            //             soc.reset_n
		.soc_id_export          (<connected-to-soc_id_export>),          //          soc_id.export
		.uart_waitrequest       (<connected-to-uart_waitrequest>),       //            uart.waitrequest
		.uart_readdata          (<connected-to-uart_readdata>),          //                .readdata
		.uart_readdatavalid     (<connected-to-uart_readdatavalid>),     //                .readdatavalid
		.uart_burstcount        (<connected-to-uart_burstcount>),        //                .burstcount
		.uart_writedata         (<connected-to-uart_writedata>),         //                .writedata
		.uart_address           (<connected-to-uart_address>),           //                .address
		.uart_write             (<connected-to-uart_write>),             //                .write
		.uart_read              (<connected-to-uart_read>),              //                .read
		.uart_byteenable        (<connected-to-uart_byteenable>),        //                .byteenable
		.uart_debugaccess       (<connected-to-uart_debugaccess>)        //                .debugaccess
	);

